# Generated by Django 3.2.25 on 2024-07-18 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='full_name',
        ),
        migrations.AddField(
            model_name='tag',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date(2024, 7, 18), verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.date(2024, 7, 18), verbose_name='date published'),
        ),
    ]
