# Generated by Django 3.2.25 on 2024-07-19 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_tag_tag_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.date(2024, 7, 19), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='pub_date',
            field=models.DateField(default=datetime.date(2024, 7, 19), verbose_name='date published'),
        ),
    ]
